"""Non-learning policy baselines and Stage 8 policy interfaces."""

from .baselines import BaselineTopology, PolicyBaselines
from .architecture_contract import (
    STAGE5_7_POLICY_ARCHITECTURE_STAGE_ID,
    STAGE5_7_RECOMMENDED_NEXT_TASK,
    STAGE5_7_VERDICT,
    build_stage5_7_policy_architecture_contract,
)
from .assembler_diagnostics import AssemblerDiagnostics, RejectionReason
from .action_semantics import (
    ACTIVE_ACTION_SEMANTICS_ID,
    UNDIRECTED_PHYSICAL_LINK_ACTION_SEMANTICS_ID,
    ActionSemanticsSpec,
    assert_action_semantics_active,
    build_active_action_semantics_registry,
    get_active_action_semantics_id,
)
from .decentralized_baselines import (
    DecentralizedBaselineResult,
    DecentralizedPolicyBaselines,
    build_local_observations,
    run_decentralized_baseline,
)
from .edge_scores import (
    EDGE_SCORE_RECORD_FIELDS,
    EdgeScoreBatch,
    EdgeScoreRecord,
    make_directed_edge_id,
)
from .interface_contract import (
    ACTOR_EDGE_SCORE_OUTPUT_SCHEMA_ID,
    ACTOR_POLICY_ALLOWED_INPUT_FIELDS,
    ACTOR_POLICY_FORBIDDEN_INPUT_FIELDS,
    ACTOR_POLICY_INPUT_SCHEMA_ID,
    ACTOR_POLICY_OUTPUT_SCHEMA_ID,
    LEGACY_ACTOR_EDGE_DECISION_OUTPUT_SCHEMA_ID,
    LEGACY_ACTOR_EDGE_DECISION_OUTPUT_FIELDS,
    STAGE8_0_ACTOR_POLICY_INTERFACE_STAGE_ID,
    STAGE8_0_RECOMMENDED_NEXT_TASK,
    STAGE8_0_VERDICT,
    PolicyInterfaceViolation,
    build_stage8_0_actor_policy_interface_contract,
    validate_actor_policy_input_fields,
    validate_actor_policy_input_row,
    validate_actor_policy_output_fields,
    validate_legacy_actor_edge_decision_output_fields,
)
from .actor_interface import (
    ActorPolicyInput,
    ActorPolicyOutput,
    PolicyState,
    validate_actor_policy_output_payload,
)
from .local_mlp_edge_scorer import (
    LOCAL_MLP_EDGE_FEATURE_FIELDS,
    LOCAL_MLP_EDGE_SCORER_ID,
    LOCAL_MLP_FEATURE_SCHEMA_ID,
    STAGE9_0_LOCAL_MLP_STAGE_ID,
    EncodedLocalEdge,
    LocalMLPEdgeScorer,
    LocalMLPEdgeScorerConfig,
    LocalMLPEdgeScorerViolation,
    build_stage9_0_local_mlp_report,
    encode_actor_local_edges,
)
from .topology_assembler import (
    DEPLOYMENT_ASSEMBLER_FORBIDDEN_FIELDS,
    AssembledTopology,
    AssemblerConfig,
    AssemblerInputViolation,
    CandidateEdgeConstraint,
    ConflictAwareGreedyAssembler,
    FixedTopKPerAgentAssembler,
    RoleAwareAdaptiveBudgetAssembler,
    ThresholdAssembler,
)
from .physical_link_assembler import (
    PHYSICAL_LINK_ASSEMBLER_ID,
    PhysicalLinkAssembly,
    PhysicalLinkConflictAwareAssembler,
    PhysicalLinkScore,
    aggregate_endpoint_scores_to_physical_links,
)

__all__ = [
    "ACTOR_EDGE_SCORE_OUTPUT_SCHEMA_ID",
    "ACTIVE_ACTION_SEMANTICS_ID",
    "DEPLOYMENT_ASSEMBLER_FORBIDDEN_FIELDS",
    "EDGE_SCORE_RECORD_FIELDS",
    "PHYSICAL_LINK_ASSEMBLER_ID",
    "UNDIRECTED_PHYSICAL_LINK_ACTION_SEMANTICS_ID",
    "ActorPolicyInput",
    "ActorPolicyOutput",
    "ActionSemanticsSpec",
    "AssembledTopology",
    "AssemblerConfig",
    "AssemblerDiagnostics",
    "AssemblerInputViolation",
    "BaselineTopology",
    "CandidateEdgeConstraint",
    "ConflictAwareGreedyAssembler",
    "DecentralizedBaselineResult",
    "DecentralizedPolicyBaselines",
    "EdgeScoreBatch",
    "EdgeScoreRecord",
    "FixedTopKPerAgentAssembler",
    "LOCAL_MLP_EDGE_FEATURE_FIELDS",
    "LOCAL_MLP_EDGE_SCORER_ID",
    "LOCAL_MLP_FEATURE_SCHEMA_ID",
    "STAGE9_0_LOCAL_MLP_STAGE_ID",
    "EncodedLocalEdge",
    "LocalMLPEdgeScorer",
    "LocalMLPEdgeScorerConfig",
    "LocalMLPEdgeScorerViolation",
    "PolicyBaselines",
    "PolicyState",
    "PhysicalLinkAssembly",
    "PhysicalLinkConflictAwareAssembler",
    "PhysicalLinkScore",
    "RejectionReason",
    "RoleAwareAdaptiveBudgetAssembler",
    "ThresholdAssembler",
    "ACTOR_POLICY_ALLOWED_INPUT_FIELDS",
    "ACTOR_POLICY_FORBIDDEN_INPUT_FIELDS",
    "ACTOR_POLICY_INPUT_SCHEMA_ID",
    "ACTOR_POLICY_OUTPUT_SCHEMA_ID",
    "LEGACY_ACTOR_EDGE_DECISION_OUTPUT_SCHEMA_ID",
    "LEGACY_ACTOR_EDGE_DECISION_OUTPUT_FIELDS",
    "STAGE5_7_POLICY_ARCHITECTURE_STAGE_ID",
    "STAGE5_7_RECOMMENDED_NEXT_TASK",
    "STAGE5_7_VERDICT",
    "STAGE8_0_ACTOR_POLICY_INTERFACE_STAGE_ID",
    "STAGE8_0_RECOMMENDED_NEXT_TASK",
    "STAGE8_0_VERDICT",
    "PolicyInterfaceViolation",
    "aggregate_endpoint_scores_to_physical_links",
    "assert_action_semantics_active",
    "build_active_action_semantics_registry",
    "build_local_observations",
    "build_stage5_7_policy_architecture_contract",
    "build_stage8_0_actor_policy_interface_contract",
    "build_stage9_0_local_mlp_report",
    "encode_actor_local_edges",
    "get_active_action_semantics_id",
    "make_directed_edge_id",
    "run_decentralized_baseline",
    "validate_actor_policy_input_fields",
    "validate_actor_policy_input_row",
    "validate_actor_policy_output_fields",
    "validate_actor_policy_output_payload",
    "validate_legacy_actor_edge_decision_output_fields",
]
